version: '3.9'

services:
  psql:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mpj_dev
      POSTGRES_PASSWORD: mpj_dev
      POSTGRES_DATABASE: mpj_dev
    networks:
      - database

  apiserver:
    build: .
    command:
      - run -c /app/configs/mpj.yml
    ports:
      - 9090:9090
    volumes:
      - .:/app
      - gocache:/root/.cache
      - go:/go
    networks:
    - core
    - database

volumes:
  go:
  gocache:
  redpanda:

networks:
  core:
  database:
