version: '3.9'

services:
  psql:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${NAME}_dev
      POSTGRES_PASSWORD: ${NAME}_dev
      POSTGRES_DATABASE: ${NAME}_dev
    networks:
      - database

  apiserver:
    build: .
    command:
      - run -c /app/configs/${NAME}.yml
    ports:
      - 9090:9090
    volumes:
      - .:/app
      - gocache:/root/.cache
      - go:/go
    networks:
    - core
    - database

volumes:
  go:
  gocache:

networks:
  core:
  database:
