#!/bin/bash

NAME="$1"
CURRENT_NAME="mpj"

REPOSITORY="https://github.com/m-vinc/go-rest-template"
BRANCH="master"
REQUIREMENTS="docker docker-compose"

if ! [[ "$NAME" =~ ^[[:lower:][:digit:]]{3,15}$ ]]; then
    echo "name must be a lowercase string between 3 and 15 characters long."
    exit 1
fi

for r in $REQUIREMENTS; do
    echo -n "checking for $r in PATH ..."
    if ! [ -x "$(command -v $r)" ]; then
        echo "ko"
        echo "$r not found in PATH"
        exit 1
    fi
    echo "ok"
done

if [ -d "$NAME" ]; then
    echo "$NAME already exist"
    exit 1
fi

git clone --branch "$BRANCH" "$REPOSITORY" "$NAME"

cd "$NAME"

mv -v "./cmd/$CURRENT_NAME-apiserver" "./cmd/$NAME-apiserver"

echo "Writing .env file for docker-compose"
cat <<EOF > .env
COMPOSE_PROJECT_NAME=${NAME}
NAME=${NAME}
EOF

echo "Writing .gitignore"
cat <<EOF > .gitignore
/dist
/cmd/${NAME}-apiserver/${NAME}-apiserver
/cmd/${NAME}ctl/${NAME}ctl
/deployments/production/secrets/*.yml
.DS_Store

/configs/${NAME}.production.yml
/configs/${NAME}.staging.yml
/deployments/staging/secrets/${NAME}-staging.raw.yml
/deployments/staging/secrets/${NAME}-staging.yml
EOF

echo "Writing configuration file"
cat <<EOF > ./configs/${NAME}.yml
application:
  bind: ":9090"
  master_key: your_secret_key_used_for_many_things
  env: dev

postgres:
  host: psql
  port: "5432"
  database: ${NAME}_dev
  username: ${NAME}_dev
  password: ${NAME}_dev
  ssl_mode: disable
EOF

echo "Writing docker-entrypoint"

cat <<EOF > ./scripts/docker-entrypoint.sh
#!/bin/bash

set -e

arelo -d 2s -p 'configs/*.yml' -p '**/*.go' -i '**/*_test.go' --  bash -c "go run -tags dynamic cmd/${NAME}-apiserver/*.go \$@"
EOF

docker-compose build
docker-compose run --entrypoint bash apiserver -c 'gorename -print-result -use-modules -new-path "demo" -path mpj && go generate ./...'

rm -vf ./scripts/init
rm -rf .git

git init
git add .
git commit -m "init"
